### ISSUE TITLE
Airspeed Indicator Tape.svg missing numbers

### ISSUE THREAD

**Issue by Kovinator** [CaptainBobSim/The-Cessna-172-Project-V3#104]
The Airspeed Indicator Tape.svg in the decals folder is missing numbers on the top here on github and on thingiverse. FYI If you look at Airspeed Indicator Single Sheet.pdf in the folder it does contain the numbers. There is also a noticeable quality loss in the svg version.

**Comment by CaptainBobSim** [comment]
Thanks for the heads up! This has been put on my todo list

**Comment by CaptainBobSim** [comment]
![image](https://user-images.githubusercontent.com/76851401/171970323-894d29ac-dde5-4a57-9964-ceaa127b6515.png)
It looks all good on my end. It might be an inkscape to normal svg problem. I'll export as a normal SVG

**Comment by CaptainBobSim** [comment]
I exported this as a plain svg.
