### ISSUE TITLE
EGT Indicator Question

### ISSUE THREAD

**Issue by Kovinator** [CaptainBobSim/The-Cessna-172-Project-V3#155]
How does the EGT knob feel when you turn it in the real aircraft? Does it click as you rotate the knob thus moving the needle or is it smooth? Does anyone know? I'm almost done with the 9g servo version of the EGT just need to know this to complete it. If we don't know then I'll probably make it smooth because it would be an easier design. I already have a clickable version but it is going to be tricky to work out so that it clicks and thus steps properly on each line on the decal.

**Comment by CaptainBobSim** [comment]
my assumption is that it is smooth, but I will check my PPL course to be sure.

**Comment by CaptainBobSim** [comment]
It looks like it can be between lines: 
![image](https://user-images.githubusercontent.com/76851401/194922508-2a108ab3-9f76-4f94-a3d6-0b20afcd8641.png)
It shouldn't have to snap to lines
