### ISSUE TITLE
Missing Fuel Indicator Decal

### ISSUE THREAD

**Issue by CaptainBobSim** [CaptainBobSim/The-Cessna-172-Project-V3#262]
I prolly deleted it....
Whoop

**Comment by Kovinator** [comment]
ah man I wish I would have caught this before I updated. Its deleted on my end too now!

**Comment by Kovinator** [comment]
Look into TEMPLETE simple instrument. you can find it there. needs to be modified again to make it closer to the real instrument.

**Comment by Kovinator** [comment]
Checking to see if I have a backup somewhere

**Comment by Kovinator** [comment]
found it doing pull request

**Comment by CaptainBobSim** [comment]
Thank you for adding it back! I'll try to be less clumsy in the future!
