### ISSUE TITLE
Attitude Indicator cutout should have slot also turn coord

### ISSUE THREAD

**Issue by CaptainBobSim** [CaptainBobSim/The-Cessna-172-Project-V3#270]

**Comment by callahanp** [comment]
This is a photo of an instrument Shock Panel from a C172.  The part number is not identified on the part, so it may or may not be Cessna 172 Removable Instrument Shock Panel Assembly, P/N: 0513554-1  Which was current on the C172P in 1983, or it may be from an earlier or later model.

![C172_x_InstrumentShockPanel](https://user-images.githubusercontent.com/6132176/235161165-77ded152-af2e-4705-87c4-1342d7e8fd2f.jpg)

**Comment by CaptainBobSim** [comment]
Nice!
The ruler comes in handy.

**Comment by CaptainBobSim** [comment]
Finished!
