### ISSUE TITLE
COM NAV GND Fault? Make sure COM Encoder works before GNS 530 PCB Release

### ISSUE THREAD

**Issue by CaptainBobSim** [CaptainBobSim/The-Cessna-172-Project-V3#486]

**Comment by ecdcrew** [comment]
Do you do "auto route" on easyEDA? Some times the distance between paths does run an electrical short (like 1 in every 30 PCBS)

**Comment by CaptainBobSim** [comment]
I forgot I still had this opened! It was actually an issue that I didn't have it configured in Mobiflight 🤦‍♂️
